### ISSUE TITLE
sirius output in Hartree interleaved with QE output in Ry

### ISSUE THREAD

**Issue by ltalirz** [electronic-structure/q-e-sirius#16]
Sirius output like

```
250            -3954.3985137916948      -2.8991120973072e-03 -1.0000000000000e+00
         kT * S       : 0.0007437037132
         Fermi energy : 0.5005476392783
         KS energy    : -3954.3992574954082
```

is interleaved with QE information like

```
!    total energy              =   -7908.79408092 Ry
```

This can be confusing to users.

I suggest to 

- [ ] Report units in the Sirius output
- [ ] Possibly convert units in Sirius output to Ry
- [ ] Add descriptions of what the three floating point numbers mean (considering also that people might want to grep for it in the output file)

**Comment by simonpintarelli** [comment]
Hi @ltalirz! Thanks a lot for your suggestions. This output is coming from nlcglib. I've opened the issue there: https://github.com/simonpintarelli/nlcglib/issues/6
